# Build Darkly and publish release
name: Darkly AUR CI
on:
  schedule:
    - cron: "0 00 * * *" # At 00:00 daily
env:
  AUR_DARKLY_REPO: https://aur.archlinux.org/darkly.git
  AUR_DARKLY_BIN_REPO: https://aur.archlinux.org/darkly-bin.git
  GIT_USER: DeltaCopy
  GIT_EMAIL: 7x0bb03yq@mozmail.com
  BUILD_REPO: https://github.com/Bali10050/darkly
jobs:
  darkly-aur-ci:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout local
        uses: actions/checkout@v4.2.0
        with:
          repository: ${{ github.repository }}
          sparse-checkout: .github/assets
          sparse-checkout-cone-mode: false

      - name: System update
        run: pacman -Syu --noconfirm
      - name: Install sudo, git and compile dependencies
        run: |
          # openssh required for creating the ssh aur config
          # base-devel includes build dependencies (fakeroot, make, gcc, pkgconf)
          pacman -Syq base-devel openssh git --noconfirm

      - name: Setup build user
        run: |
          useradd --create-home --shell /bin/bash builduser -m # Create the builduser
          passwd -d builduser # Delete the buildusers password
          printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # Allow the builduser passwordless sudo

      - name: Create SSH AUR config & clone
        env:
          AUR_PRIV: ${{ secrets.AUR_P1 }}
        run: |
          mkdir -p /home/builduser/.ssh
          touch /home/builduser/.ssh/known_hosts
          cp $GITHUB_WORKSPACE/.github/assets/ssh_config /home/builduser/.ssh/config

          chmod -vR 600 /home/builduser/.ssh/* 

          ssh-keyscan -v -t rsa,ecdsa,ed25519 aur.archlinux.org >>/home/builduser/.ssh/known_hosts

          echo "$AUR_PRIV" > /home/builduser/.ssh/aur
          chmod -R 600 /home/builduser/.ssh/aur*

          ssh-keygen -vy -f /home/builduser/.ssh/aur > /home/builduser/.ssh/aur.pub

          chown -vR builduser:builduser /home/builduser

      - name: Git clone AUR repos
        run: |
          sudo -u builduser bash -c 'git clone ${{ env.AUR_DARKLY_REPO }} /tmp/darkly'
          sudo -u builduser bash -c 'git clone ${{ env.AUR_DARKLY_BIN_REPO }} /tmp/darkly-bin'

          git config --global --add safe.directory '/tmp/darkly'
          git config --global --add safe.directory '/tmp/darkly-bin'

          git config --global user.name ${{ env.GIT_USER}}
          git config --global user.email ${{ env.GIT_EMAIL}}

      - name: Update package files
        run: |
          latest_release_tag=$(git -c 'versionsort.suffix=-' ls-remote --exit-code --refs --sort='version:refname' --tags $BUILD_REPO '*.*' \
                      | tail --lines=1 | cut --delimiter='/' --fields=3)

          cp $GITHUB_WORKSPACE/.github/assets/darkly/PKGBUILD.template /tmp/darkly/PKGBUILD
          cp $GITHUB_WORKSPACE/.github/assets/darkly/.SRCINFO.template /tmp/darkly/.SRCINFO

          cp $GITHUB_WORKSPACE/.github/assets/darkly-bin/PKGBUILD.template /tmp/darkly-bin/PKGBUILD
          cp $GITHUB_WORKSPACE/.github/assets/darkly-bin/.SRCINFO.template /tmp/darkly-bin/.SRCINFO

          if [ ! -z $latest_release_tag ]; then
            latest_tag=$(echo $latest_release_tag | sed 's/v//')
            echo "RELEASE_VERSION=${latest_release_tag}" >> "$GITHUB_ENV"
            sed -i 's/${version}/'${latest_tag}'/' /tmp/darkly/PKGBUILD
            sed -i 's/${version}/'${latest_tag}'/' /tmp/darkly/.SRCINFO
            
            sha256sum_darkly=$(curl -Ls $BUILD_REPO/archive/refs/tags/v${latest_tag}.tar.gz | sha256sum | awk {'print $1'})

            sed -i 's/${sha256sums}/'${sha256sum_darkly}'/' /tmp/darkly/PKGBUILD
            sed -i 's/${sha256sums}/'${sha256sum_darkly}'/' /tmp/darkly/.SRCINFO


            sed -i 's/${version}/'${latest_tag}'/' /tmp/darkly-bin/PKGBUILD
            sed -i 's/${version}/'${latest_tag}'/' /tmp/darkly-bin/.SRCINFO
            sed -i 's/darkly-${version}/darkly-'${latest_tag}'/' /tmp/darkly-bin/.SRCINFO
            
            sha256sum_darkly_bin=$(curl -Ls $BUILD_REPO/releases/download/v${latest_tag}/darkly-${latest_tag}-x86_64.pkg.zst | sha256sum | awk {'print $1'})

            sed -i 's/${sha256sums}/'${sha256sum_darkly_bin}'/' /tmp/darkly-bin/PKGBUILD
            sed -i 's/${sha256sums}/'${sha256sum_darkly_bin}'/' /tmp/darkly-bin/.SRCINFO

          fi

          chown -R builduser:builduser /tmp/darkly
          chown -R builduser:builduser /tmp/darkly-bin

      - name: Print pkgbuild & .srcinfo
        run: |
          echo "#############################"

          cat /tmp/darkly/PKGBUILD
          cat /tmp/darkly/.SRCINFO

          echo "#############################"

          cat /tmp/darkly-bin/PKGBUILD
          cat /tmp/darkly-bin/.SRCINFO

      - name: Set parallel makeflags
        run: sed -i 's/.*MAKEFLAGS=.*/MAKEFLAGS="-j $(nproc)"/' /etc/makepkg.conf

      - name: Test darkly build
        run: |
          sudo -u builduser bash -c 'cd /tmp/darkly; makepkg -s --noconfirm; test $? -eq 0 && touch /tmp/.darklybuild'
          echo "DARKLY_MODIFIED=$(git -C /tmp/darkly status -s PKGBUILD | wc -l)" >> "$GITHUB_ENV"

      - name: Publish AUR package darkly
        if: env.DARKLY_MODIFIED == 1
        run: |
          echo "Changes found, publish required."
          if [ -f  /tmp/.darklybuild ]; then
            sudo -u builduser bash -c 'cd /tmp/darkly; git remote add aur "ssh://aur@aur.archlinux.org/darkly.git"; \
            git config --global user.name ${{ env.GIT_USER}}
            git config --global user.email ${{ env.GIT_EMAIL}}
            git add -fv PKGBUILD .SRCINFO && git commit -m "[GitHub DeltaCopy/darkly-aur-ci]: Version ${{ env.RELEASE_VERSION }}" && git push -v aur master'
          fi

      - name: Test darkly-bin build
        run: |
          sudo -u builduser bash -c 'cd /tmp/darkly-bin; makepkg -s --noconfirm; test $? -eq 0 && touch /tmp/.darklybin-build'
          echo "DARKLY_BIN_MODIFIED=$(git -C /tmp/darkly-bin status -s PKGBUILD | wc -l)" >> "$GITHUB_ENV"

      - name: Publish AUR package darkly-bin
        if: env.DARKLY_BIN_MODIFIED == 1
        run: |
          echo "Changes found, publish required."
          if [ -f  /tmp/.darklybin-build ]; then
            sudo -u builduser bash -c 'cd /tmp/darkly-bin; git remote add aur "ssh://aur@aur.archlinux.org/darkly-bin.git"; \
            git config --global user.name ${{ env.GIT_USER}}
            git config --global user.email ${{ env.GIT_EMAIL}}
            git add -fv PKGBUILD .SRCINFO && git commit -m "[GitHub DeltaCopy/darkly-aur-ci]: Version ${{ env.RELEASE_VERSION }}" && git push -v aur master'
          fi
